// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx ts-node --project tsconfig.seed.json ./prisma/seed.ts",
  },
  datasource: {
    url: process.env["POSTGRES_PRISMA_URL"] || process.env["DATABASE_URL"],
    directUrl: process.env["POSTGRES_URL_NON_POOLING"],
  },
});
